version: '3'
services:
  goapp:
    build: .
    ports:
      - "50004:50004"
      - "3002:3002"
    networks:
      - hello-dapr
  goapp-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
      "-app-id", "goapp",
      "-app-port", "3002",
      "-placement-host-address", "placement:50006",
      "-dapr-grpc-port", "50004",
      "-components-path", "/components"]
    volumes:
      - "./components/:/components"
    depends_on:
      - goapp
    network_mode: "service:goapp"
networks:
  hello-dapr:
    external: true