version: '3'
services:
  denoapp:
    build: .
    ports:
      - "50003:50003"
      - "3001:3001"
    networks:
      - hello-dapr
  denoapp-dapr:
    image: "daprio/daprd:edge"
    command: ["./daprd",
     "-app-id", "denoapp",
     "-app-port", "3001",
     "-placement-host-address", "placement:50006",
     "-dapr-grpc-port", "50003",
     "-components-path", "/components"]
    volumes:
      - "./components/:/components"
    depends_on:
      - denoapp
    network_mode: "service:denoapp"
networks:
  hello-dapr:
    external: true